### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by davelab6**
Per @patrykdesign the RFN can be removed

### CODE REVIEW

**Comment by davelab6** [comment]
https://github.com/mozilla/Fira/issues/221 confirmed this, so this is good to merge.

**Comment by davelab6** [comment]
Who can merge this?

**Comment by thundernixon** [comment]
@jdashg would you be able to merge this, by any chance? If not, could you potentially cc someone who can?

It's currently blocking Fira Code from being published to Google Fonts (PR: https://github.com/google/fonts/pull/1911), which is making a lot of developers sad (see reactions at https://github.com/google/fonts/issues/1460).

**Comment by Ir1d** [comment]
Hi, any chance to merge this?

**Pull request merged**
